# Generated by Django 5.1.2 on 2024-10-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_shift_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shift_working',
        ),
    ]
